"""add_customer_name_and_order_type_to_orders

Revision ID: 8161f872a08d
Revises: e2fc30e12ba0
Create Date: 2025-09-26 14:34:09.376517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8161f872a08d'
down_revision: Union[str, None] = 'e2fc30e12ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_type')
    op.drop_column('orders', 'customer_name')
    # ### end Alembic commands ###
