"""add_kitchen_print_enabled_to_restaurant

Revision ID: 9a6f610ba1a3
Revises: add_order_persons
Create Date: 2025-11-18 13:28:22.204312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6f610ba1a3'
down_revision: Union[str, None] = 'add_order_persons'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('kitchen_print_enabled', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('restaurants', sa.Column('kitchen_print_paper_width', sa.Integer(), nullable=False, server_default='80'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'kitchen_print_paper_width')
    op.drop_column('restaurants', 'kitchen_print_enabled')
    # ### end Alembic commands ###
