"""make_table_id_nullable

Revision ID: c5f8ae061bff
Revises: 8161f872a08d
Create Date: 2025-10-09 19:12:04.207971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c5f8ae061bff'
down_revision: Union[str, None] = '8161f872a08d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'table_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'table_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
