"""Update category enum values

Revision ID: dd65ac7c85f2
Revises: 1ef8e8597177
Create Date: 2025-08-29 22:33:16.705110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd65ac7c85f2'
down_revision: Union[str, None] = '1ef8e8597177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # For MySQL, we need to use MODIFY COLUMN instead of ALTER COLUMN
    op.execute("""
        ALTER TABLE menu_items 
        MODIFY COLUMN category VARCHAR(50)
    """)
    # MySQL doesn't have DROP TYPE, so we'll create a temporary column
    op.execute("""
        ALTER TABLE menu_items 
        CHANGE category category_temp VARCHAR(50)
    """)
    # Create the new enum column
    op.execute("""
        ALTER TABLE menu_items 
        ADD COLUMN category ENUM('COFFEE', 'TEA', 'PASTRY', 'SANDWICH', 'DESSERT', 'OTHER')
    """)
    # Copy data from the temporary column to the new column
    op.execute("""
        UPDATE menu_items 
        SET category = category_temp
        WHERE category_temp IS NOT NULL
    """)
    # Drop the temporary column
    op.execute("""
        ALTER TABLE menu_items 
        DROP COLUMN category_temp
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a temporary column for the old enum values
    op.execute("""
        ALTER TABLE menu_items 
        ADD COLUMN category_temp ENUM('FOOD', 'DRINK', 'DESSERT')
    """)
    # Map the new values to the old enum values
    op.execute("""
        UPDATE menu_items 
        SET category_temp = 
            CASE 
                WHEN category IN ('coffee', 'tea') THEN 'DRINK'
                WHEN category IN ('sandwich', 'pastry') THEN 'FOOD'
                WHEN category = 'dessert' THEN 'DESSERT'
                ELSE 'FOOD'
            END
    """)
    # Drop the new column
    op.execute("""
        ALTER TABLE menu_items 
        DROP COLUMN category
    """)
    # Rename the temporary column back to the original name
    op.execute("""
        ALTER TABLE menu_items 
        CHANGE category_temp category ENUM('FOOD', 'DRINK', 'DESSERT')
    """)
    # ### end Alembic commands ###
