"""add_payment_method_to_orders

Revision ID: e2fc30e12ba0
Revises: 01e6bf410b36
Create Date: 2025-09-26 14:22:05.251552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2fc30e12ba0'
down_revision: Union[str, None] = '01e6bf410b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_register_reports', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('cash_register_reports', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('cash_register_reports', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_cash_register_reports_id'), 'cash_register_reports', ['id'], unique=False)
    op.add_column('cash_register_sessions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('cash_register_sessions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('cash_register_sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('cash_register_sessions', 'initial_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('cash_register_sessions', 'expected_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('cash_register_sessions', 'status',
               existing_type=mysql.ENUM('open', 'closed'),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_cash_register_sessions_id'), 'cash_register_sessions', ['id'], unique=False)
    op.add_column('cash_transactions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('cash_transactions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('cash_transactions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_cash_transactions_id'), 'cash_transactions', ['id'], unique=False)
    op.add_column('orders', sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'DIGITAL', 'OTHER', name='payment_method'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_method')
    op.drop_index(op.f('ix_cash_transactions_id'), table_name='cash_transactions')
    op.drop_column('cash_transactions', 'deleted_at')
    op.drop_column('cash_transactions', 'updated_at')
    op.drop_column('cash_transactions', 'created_at')
    op.drop_index(op.f('ix_cash_register_sessions_id'), table_name='cash_register_sessions')
    op.alter_column('cash_register_sessions', 'status',
               existing_type=mysql.ENUM('open', 'closed'),
               server_default=sa.text("'open'"),
               existing_nullable=False)
    op.alter_column('cash_register_sessions', 'expected_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               server_default=sa.text("'0.00'"),
               existing_nullable=False)
    op.alter_column('cash_register_sessions', 'initial_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               server_default=sa.text("'0.00'"),
               existing_nullable=False)
    op.drop_column('cash_register_sessions', 'deleted_at')
    op.drop_column('cash_register_sessions', 'updated_at')
    op.drop_column('cash_register_sessions', 'created_at')
    op.drop_index(op.f('ix_cash_register_reports_id'), table_name='cash_register_reports')
    op.drop_column('cash_register_reports', 'deleted_at')
    op.drop_column('cash_register_reports', 'updated_at')
    op.drop_column('cash_register_reports', 'created_at')
    # ### end Alembic commands ###
