"""Fix category nullable constraint

Revision ID: e99b53354714
Revises: dd65ac7c85f2
Create Date: 2025-08-29 22:38:32.875669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e99b53354714'
down_revision: Union[str, None] = 'dd65ac7c85f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu_items', 'category',
               existing_type=mysql.ENUM('coffee', 'tea', 'pastry', 'sandwich', 'dessert', 'other', collation='utf8mb4_unicode_ci'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu_items', 'category',
               existing_type=mysql.ENUM('coffee', 'tea', 'pastry', 'sandwich', 'dessert', 'other', collation='utf8mb4_unicode_ci'),
               nullable=True)
    # ### end Alembic commands ###
