"""fix_categories_migration

Revision ID: f8aed4bfdec9
Revises: bf3105713eda
Create Date: 2025-08-29 23:25:10.693295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f8aed4bfdec9'
down_revision: Union[str, None] = 'bf3105713eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('categories', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('name', table_name='categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'categories', ['name'], unique=False)
    op.alter_column('categories', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('categories', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    # ### end Alembic commands ###
